<a href="https://colab.research.google.com/github/sangeerthP-10/Data_Science_Internship/blob/main/Data_science_internship_(day_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KNN Classifier

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('BMI.csv')
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [3]:
df.shape

(500, 4)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64
 2   Weight  500 non-null    int64
 3   Index   500 non-null    int64
dtypes: int64(3), object(1)
memory usage: 15.8+ KB

In [5]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df['Gender']=LE.fit_transform(df['Gender'])
print(df.head())

   Gender  Height  Weight  Index
0       1     174      96      4
1       1     189      87      2
2       0     185     110      4
3       0     195     104      3
4       1     149      61      3

In [7]:
df.corr()

          Gender    Height    Weight     Index
Gender  1.000000 -0.017677  0.009523  0.028786
Height -0.017677  1.000000  0.000446 -0.422223
Weight  0.009523  0.000446  1.000000  0.804569
Index   0.028786 -0.422223  0.804569  1.000000

In [12]:
x=df[['Gender','Height','Weight']]
y=df.Index

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
KNN.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [14]:
ypred=KNN.predict(x_test)
print(ypred)

[5 4 4 2 5 4 5 1 4 5 5 3 5 4 4 4 2 5 5 3 4 4 5 0 5 4 5 4 4 3 3 5 3 5 4 5 2
 3 4 5 2 2 5 4 5 3 5 5 2 5 4 0 3 2 5 0 2 5 5 3 2 0 5 5 1 5 2 5 4 3 4 4 5 5
 5 5 5 1 4 5 5 5 3 4 2 5 4 5 5 5 2 5 2 5 5 4 4 3 5 4]

In [18]:
from sklearn.metrics import classification_report,accuracy_score
print(accuracy_score(y_test,ypred))

0.91