<a href="https://colab.research.google.com/github/sangeerthP-10/Data_Science_Internship/blob/main/Data_science_internship_(day_23%2C24).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd

In [34]:
df=pd.read_csv('apples_and_oranges.csv')
df.head()

   Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

In [35]:
df.shape

(40, 3)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  40 non-null     int64
 1   Size    40 non-null     float64
 2   Class   40 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ KB

In [37]:
df.isnull().sum()

Weight    0
Size      0
Class     0
dtype: int64

In [38]:
df.describe()

          Weight       Size
count  40.000000  40.000000
mean   70.200000   4.922750
std     3.039906   0.590063
min    65.000000   4.010000
25%    68.000000   4.360000
50%    70.000000   4.930000
75%    73.000000   5.472500
max    75.000000   5.850000

In [39]:
from sklearn.preprocessing import LabelEncoder
en=LabelEncoder()
df['Class']=en.fit_transform(df['Class'])

In [40]:
df.head()

   Weight  Size  Class
0      69  4.39      1
1      69  4.21      1
2      65  4.09      1
3      72  5.85      0
4      67  4.70      1

In [41]:
from sklearn.model_selection import train_test_split
x=df[['Weight','Size']]
y=df['Class']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

Linear SVM

In [42]:
from sklearn.svm import LinearSVC
classifier=LinearSVC()
classifier.fit(x_train,y_train)

LinearSVC()

In [43]:
from sklearn.metrics import accuracy_score
y_pred=classifier.predict(x_test)
accuracy_score(y_test,y_pred)

0.75

confusion matrix

In [44]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_pred)

array([[2, 0],
       [2, 4]])

In [45]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.50      1.00      0.67         2\n           1       1.00      0.67      0.80         6\n\n    accuracy                           0.75         8\n   macro avg       0.75      0.83      0.73         8\nweighted avg       0.88      0.75      0.77         8\n'

Non linear SVM

In [46]:
df_iris=pd.read_csv('Iris.csv')
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [47]:
from sklearn.svm import LinearSVC,SVC
X=df_iris.iloc[:,0:5]
Y=df_iris['Species']
lin_SVC=LinearSVC().fit(X,Y)
svc_lin=SVC(kernel='linear').fit(X,Y)#linear decison boundary for seperating data

svc_rbf=SVC(kernel='rbf').fit(X,Y)#non linear boundary

svc_poly1=SVC(kernel='poly',degree=4).fit(X,Y)


svc_poly2=SVC(kernel='poly',degree=4).fit(X,Y)

In [48]:
lin_SVC.score(X,Y)

1.0

In [49]:
svc_lin.score(X,Y)

1.0

In [50]:
svc_rbf.score(X,Y)

1.0

In [51]:
svc_poly1.score(X,Y)

0.96

In [52]:
svc_poly2.score(X,Y)

0.96