<a href="https://colab.research.google.com/github/sangeerthP-10/Data_Science_Internship/blob/main/Data_science_internship_(day_18%2C_day_19%2Cday_20%2Cday_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("Housing.csv")
df

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,1,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,2,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,3,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,4,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,5,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,542,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,543,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,544,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,545,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,546,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [33]:
df.shape

(546, 13)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  546 non-null    int64
 1   price       546 non-null    float64
 2   lotsize     546 non-null    int64
 3   bedrooms    546 non-null    int64
 4   bathrms     546 non-null    int64
 5   stories     546 non-null    int64
 6   driveway    546 non-null    object
 7   recroom     546 non-null    object
 8   fullbase    546 non-null    object
 9   gashw       546 non-null    object
 10  airco       546 non-null    object
 11  garagepl    546 non-null    int64
 12  prefarea    546 non-null    object
dtypes: float64(1), int64(6), object(6)
memory usage: 55.6+ KB

In [35]:
df.describe()

,Unnamed: 0,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,273.500000,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,157.760895,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,1.000000,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,137.250000,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,273.500000,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,409.750000,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,546.000000,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

In [36]:
df.isnull().sum()

Unnamed: 0    0
price         0
lotsize       0
bedrooms      0
bathrms       0
stories       0
driveway      0
recroom       0
fullbase      0
gashw         0
airco         0
garagepl      0
prefarea      0
dtype: int64

In [37]:
df=df.iloc[:,1:]
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['driveway','recroom','fullbase','gashw','airco','prefarea']

for f in cols:
  df[f]=le.fit_transform(df[f])

In [40]:
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,1,0,1,0,0,1,0
1,38500.0,4000,2,1,1,1,0,0,0,0,0,0
2,49500.0,3060,3,1,1,1,0,0,0,0,0,0
3,60500.0,6650,3,1,2,1,1,0,0,0,0,0
4,61000.0,6360,2,1,1,1,0,0,0,0,0,0

Simple Linear Regression

In [41]:
df.corr()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
price,1.000000,0.535796,0.366447,0.516719,0.421190,0.297167,0.254960,0.186218,0.092837,0.453347,0.383302,0.329074
lotsize,0.535796,1.000000,0.151851,0.193833,0.083675,0.288778,0.140327,0.047487,-0.009201,0.221765,0.352872,0.234782
bedrooms,0.366447,0.151851,1.000000,0.373769,0.407974,-0.011996,0.080492,0.097201,0.046028,0.160412,0.139117,0.078953
bathrms,0.516719,0.193833,0.373769,1.000000,0.324066,0.041955,0.126892,0.102791,0.067365,0.184955,0.178178,0.064013
stories,0.421190,0.083675,0.407974,0.324066,1.000000,0.122499,0.042281,-0.173860,0.018261,0.296216,0.043412,0.042940
driveway,0.297167,0.288778,-0.011996,0.041955,0.122499,1.000000,0.091959,0.043428,-0.011942,0.106290,0.203682,0.199378
recroom,0.254960,0.140327,0.080492,0.126892,0.042281,0.091959,1.000000,0.372434,-0.010119,0.136626,0.038122,0.161292
fullbase,0.186218,0.047487,0.097201,0.102791,-0.173860,0.043428,0.372434,1.000000,0.004677,0.045248,0.052524,0.228651
gashw,0.092837,-0.009201,0.046028,0.067365,0.018261,-0.011942,-0.010119,0.004677,1.000000,-0.130350,0.068144,-0.059170
airco,0.453347,0.221765,0.160412,0.184955,0.296216,0.106290,0.136626,0.045248,-0.130350,1.000000,0.156596,0.115626
garagepl,0.383302,0.352872,0.139117,0.178178,0.043412,0.203682,0.038122,0.052524,0.068144,0.156596,1.000000,0.092364
prefarea,0.329074,0.234782,0.078953,0.064013,0.042940,0.199378,0.161292,0.228651,-0.059170,0.115626,0.092364,1.000000

In [42]:
x=df[['lotsize']]
y=df[['price']]

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [47]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [48]:
LR.coef_

array([[6.42524533]])

In [49]:
LR.intercept_

array([34421.68061292])

In [50]:
y_pred=LR.predict(x_test)
y_pred

array([[ 57777.44737249],
       [ 57873.82605238],
       [ 86466.16775254],
       [ 48203.83183693],
       [ 89550.28550897],
       [ 54853.96074922],
       [ 79398.39789408],
       [ 79398.39789408],
       [ 56781.53434698],
       [ 62178.74042072],
       [ 60122.66191644],
       [ 60122.66191644],
       [ 56910.0392535 ],
       [ 60032.70848188],
       [ 48300.21051682],
       [ 75035.6563178 ],
       [ 76828.29976372],
       [ 59158.87511756],
       [ 57745.32114586],
       [ 76442.78504417],
       [ 57809.57359912],
       [ 82122.70191225],
       [ 69118.00537267],
       [ 77599.32920283],
       [ 60122.66191644],
       [ 59351.63247733],
       [ 74605.16488097],
       [ 82225.50583746],
       [ 81068.9616788 ],
       [ 58484.22435834],
       [ 57745.32114586],
       [ 76828.29976372],
       [ 57359.80642631],
       [ 58837.61285126],
       [ 60122.66191644],
       [ 76924.67844361],
       [ 69760.52990526],
       [ 57873.82605238],
       [ 85695.13831344],
       [ 69760.52990526],
       [ 57552.56378609],
       [ 53697.41659056],
       [ 61793.22570117],
       [ 76185.77523114],
       [ 66676.41214883],
       [ 75286.24088551],
       [ 78948.63072126],
       [ 63335.28457938],
       [ 57681.0686926 ],
       [ 52926.38715145],
       [ 65359.23685703],
       [ 62307.24532724],
       [ 67511.6940412 ],
       [ 67832.95630749],
       [ 54339.94112315],
       [ 56781.53434698],
       [ 50613.29883414],
       [ 58786.21088865],
       [ 56974.29170676],
       [ 53697.41659056],
       [ 52862.13469819],
       [112102.8966028 ],
       [ 72973.1525682 ],
       [ 64620.33364455],
       [ 72973.1525682 ],
       [ 76828.29976372],
       [ 74322.45408663],
       [ 70917.07406392],
       [ 88393.74135031],
       [ 63977.80911197],
       [ 76057.27032462],
       [ 56781.53434698],
       [ 82495.36614115],
       [ 62692.76004679],
       [ 76507.03749743],
       [ 50035.02675481],
       [ 53697.41659056],
       [ 52926.38715145],
       [ 56781.53434698],
       [ 62692.76004679],
       [ 53697.41659056],
       [ 55560.73773506],
       [ 76924.67844361],
       [ 58709.10794474],
       [ 72202.12312909],
       [ 57449.75986087],
       [ 57745.32114586],
       [ 72973.1525682 ],
       [ 79398.39789408],
       [108054.9920475 ],
       [ 79398.39789408],
       [ 57552.56378609],
       [ 74515.21144641],
       [ 90963.83948066],
       [ 48203.83183693],
       [ 78370.35864194],
       [ 60122.66191644],
       [ 87429.95455143],
       [ 76185.77523114],
       [ 54140.75851804],
       [ 72973.1525682 ],
       [ 56588.7769872 ],
       [106223.79712962],
       [ 63335.28457938],
       [ 59094.6226643 ],
       [ 57745.32114586],
       [ 72973.1525682 ],
       [ 60122.66191644],
       [ 47272.17126468],
       [ 73615.67710078]])

In [53]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.29086829603208864

Prediction for house price for given lot size

In [57]:
LR.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[66547.90724232]])

Multiple Linear Regression

In [58]:
x1=df[['lotsize','bathrms']]

In [59]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y,test_size=0.2,random_state=2)
MLR=LinearRegression()
MLR.fit(x1_train,y1_train)

LinearRegression()

In [60]:
y1_pred=MLR.predict(x1_test)

In [61]:
r2_score(y1_test,y1_pred)

0.5434071368245021

In [62]:
MLR.predict([[5000,2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[81811.15796081]])